name: Run Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.head_ref || github.run_id }}-lint
  cancel-in-progress: true

jobs:
  lint:
    if: false # TODO: Enable linting once we fix all lint errors
    runs-on: ubuntu-latest
    name: Run code linting
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.10'

      - name: Run code linting
        run: |
          make lint 